steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/hybrid-essence-236114/trainer', '-f', 'trainer.dockerfile', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/hybrid-essence-236114/trainer']
